import React, { useState, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import RiskMeter from "../components/RiskMeter";
import TrendChart from "../components/TrendChart";
import Spinner from "../components/Spinner";
import usePolling from "../hooks/usePolling";

const InfoCard = ({ label, value, unit, icon, color }) => (
  <div className="glass rounded-3xl p-5 shadow-card flex items-center gap-4">
    <div className={`w-11 h-11 rounded-2xl flex items-center justify-center ${color}`}>
      {icon}
    </div>
    <div>
      <div className="text-xs text-neo-muted font-body uppercase tracking-wide">{label}</div>
      <div className="font-display font-700 text-neo-dark text-lg">
        {value} <span className="text-sm font-body text-neo-muted">{unit}</span>
      </div>
    </div>
  </div>
);

const DashboardPage = () => {
  const { user } = useAuth();
  const location = useLocation();
  const scanId = location.state?.scanId || null;

  // Polling for result if we just came from scan
  const { result, error: pollError, isPolling } = usePolling(scanId, 5000, 30);

  // Mock previous scan data for demo when no fresh scan
  const [displayData, setDisplayData] = useState({
    bilirubin: 4.8,
    riskLevel: "safe",
    confidence: 94,
    scanTime: new Date().toLocaleString(),
  });

  const [showNewResult, setShowNewResult] = useState(false);

  useEffect(() => {
    if (result) {
      setDisplayData({
        bilirubin: result.bilirubin,
        riskLevel: result.risk_level,
        confidence: Math.round(result.confidence * 100),
        scanTime: new Date().toLocaleString(),
      });
      setShowNewResult(true);
    }
  }, [result]);

  const mockTrend = [
    { date: "Day 1", value: 4.2 },
    { date: "Day 2", value: 7.8 },
    { date: "Day 3", value: 12.1 },
    { date: "Day 4", value: 10.5 },
    { date: "Day 5", value: 8.3 },
    { date: "Day 6", value: 6.1 },
    { date: "Day 7", value: displayData.bilirubin },
  ];

  const handleDownloadReport = () => {
    const content = `
NeoScan — Bilirubin Risk Report
================================
Generated: ${displayData.scanTime}
Patient: ${user?.name || "Unknown"}

RESULTS
-------
Bilirubin Estimate : ${displayData.bilirubin} mg/dL
Risk Level         : ${displayData.riskLevel.toUpperCase()}
AI Confidence      : ${displayData.confidence}%

INTERPRETATION
--------------
Safe    : < 11.5 mg/dL
Moderate: 11.5 – 15.0 mg/dL
High    : > 15.0 mg/dL

DISCLAIMER
----------
This report is generated by NeoScan, an academic prototype.
It is NOT a substitute for clinical diagnosis.
Please consult a qualified healthcare professional.
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `NeoScan_Report_${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Analyzing overlay while polling
  if (isPolling && scanId) {
    return (
      <div className="min-h-screen bg-hero-gradient flex items-center justify-center px-4">
        <div className="glass rounded-4xl p-12 shadow-glass-lg text-center max-w-md w-full animate-fade-in">
          <div className="mb-6">
            <div className="relative w-20 h-20 mx-auto">
              <div className="absolute inset-0 rounded-full border-4 border-neo-mint/30" />
              <div className="absolute inset-0 rounded-full border-4 border-t-neo-blue border-r-neo-teal animate-spin" />
              <div className="absolute inset-2 rounded-full bg-gradient-to-br from-neo-blue/10 to-neo-teal/10 flex items-center justify-center">
                <svg className="w-7 h-7 text-neo-blue fill-current" viewBox="0 0 24 24">
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 14.5v-9l6 4.5-6 4.5z" />
                </svg>
              </div>
            </div>
          </div>
          <h2 className="font-display text-2xl font-700 text-neo-dark mb-2">Analyzing Image</h2>
          <p className="text-neo-muted font-body text-sm leading-relaxed mb-6">
            Our AI is processing the scan. Color values are being extracted and calibrated.
            This typically takes 1–2 minutes.
          </p>
          <div className="flex justify-center gap-2">
            <span className="pulse-dot w-2.5 h-2.5 rounded-full bg-neo-blue" />
            <span className="pulse-dot w-2.5 h-2.5 rounded-full bg-neo-teal" />
            <span className="pulse-dot w-2.5 h-2.5 rounded-full bg-neo-mint" />
          </div>
          <p className="text-xs text-neo-muted font-body mt-4">Do not close this window</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-hero-gradient">
      <div className="max-w-5xl mx-auto px-6 pt-28 pb-16">
        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-8 gap-4 animate-slide-up">
          <div>
            <h1 className="font-display text-3xl font-800 text-neo-dark">
              {showNewResult ? "Scan Results" : "Dashboard"}
            </h1>
            <p className="text-neo-muted font-body text-sm mt-1">
              Welcome back, {user?.name || "User"} · {displayData.scanTime}
            </p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={handleDownloadReport}
              className="flex items-center gap-2 px-4 py-2.5 glass border border-neo-mint text-neo-blue font-display font-600 text-sm rounded-2xl hover:shadow-card transition-all"
            >
              <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z" />
              </svg>
              Download Report
            </button>
            <Link
              to="/calibrate"
              className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-neo-blue to-neo-teal text-white font-display font-600 text-sm rounded-2xl shadow-md hover:shadow-glass transition-all"
            >
              <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 17v-4h-2v4H9l3 3 3-3h-2zm0-14V1h-2v4H9l3-3 3 3h-2z" />
              </svg>
              New Scan
            </Link>
          </div>
        </div>

        {/* Error from polling */}
        {pollError && (
          <div className="mb-6 p-4 bg-rose-50 border border-rose-200 rounded-2xl text-rose-600 font-body text-sm">
            ⚠ {pollError}
          </div>
        )}

        {/* New result banner */}
        {showNewResult && (
          <div className="mb-6 p-4 bg-emerald-50 border border-emerald-200 rounded-2xl text-emerald-700 font-body text-sm flex items-center gap-3 animate-fade-in">
            <span className="text-xl">✓</span>
            <span>Scan analysis complete! Results are displayed below.</span>
          </div>
        )}

        {/* Main grid */}
        <div className="grid md:grid-cols-3 gap-6 mb-6">
          {/* Risk Meter - takes 1 col */}
          <div className="animate-fade-in">
            <RiskMeter
              bilirubinValue={displayData.bilirubin}
              riskLevel={displayData.riskLevel}
              confidence={displayData.confidence}
            />
          </div>

          {/* Info cards - takes 2 cols */}
          <div className="md:col-span-2 space-y-4 animate-slide-up" style={{ animationDelay: "100ms" }}>
            <div className="grid grid-cols-2 gap-4">
              <InfoCard
                label="Bilirubin"
                value={displayData.bilirubin.toFixed(1)}
                unit="mg/dL"
                color="bg-neo-blue/10 text-neo-blue"
                icon={<svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L8 8H5l7 13 7-13h-3L12 2zm0 4.5l1.76 3H10.24L12 6.5z"/></svg>}
              />
              <InfoCard
                label="Risk Level"
                value={displayData.riskLevel.charAt(0).toUpperCase() + displayData.riskLevel.slice(1)}
                unit=""
                color={
                  displayData.riskLevel === "safe"
                    ? "bg-emerald-100 text-emerald-600"
                    : displayData.riskLevel === "moderate"
                    ? "bg-amber-100 text-amber-600"
                    : "bg-rose-100 text-rose-600"
                }
                icon={<svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg>}
              />
              <InfoCard
                label="AI Confidence"
                value={displayData.confidence}
                unit="%"
                color="bg-neo-teal/10 text-neo-teal"
                icon={<svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M21 3H3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-9 14H5v-2h7v2zm7-4H5v-2h14v2zm0-4H5V7h14v2z"/></svg>}
              />
              <InfoCard
                label="Scan Time"
                value="< 2 min"
                unit=""
                color="bg-purple-100 text-purple-600"
                icon={<svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67V7z"/></svg>}
              />
            </div>

            {/* Risk explanation */}
            <div
              className={`rounded-3xl p-5 border ${
                displayData.riskLevel === "safe"
                  ? "bg-emerald-50 border-emerald-200"
                  : displayData.riskLevel === "moderate"
                  ? "bg-amber-50 border-amber-200"
                  : "bg-rose-50 border-rose-200"
              }`}
            >
              <h4 className="font-display font-700 text-neo-dark text-sm mb-1">Clinical Interpretation</h4>
              <p className="text-sm font-body leading-relaxed text-neo-muted">
                {displayData.riskLevel === "safe" &&
                  "Bilirubin levels appear within safe range. Routine monitoring is recommended. Continue normal feeding and observe skin/sclera color."}
                {displayData.riskLevel === "moderate" &&
                  "Bilirubin levels are elevated. Phototherapy may be considered. Consult with a neonatologist for clinical evaluation."}
                {displayData.riskLevel === "high" &&
                  "High bilirubin levels detected. Immediate clinical evaluation is strongly recommended. Contact a healthcare provider urgently."}
              </p>
              <p className="text-xs text-neo-muted/70 font-body mt-2 italic">
                ⚠ This is an AI estimate — not a substitute for clinical diagnosis.
              </p>
            </div>
          </div>
        </div>

        {/* Trend Chart */}
        <div
          className="glass rounded-3xl p-6 shadow-card animate-fade-in"
          style={{ animationDelay: "200ms" }}
        >
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="font-display font-700 text-neo-dark">7-Day Bilirubin Trend</h3>
              <p className="text-xs text-neo-muted font-body mt-0.5">Estimated readings over the past week</p>
            </div>
            <span className="text-xs bg-neo-blue/10 text-neo-blue font-display font-600 px-3 py-1 rounded-full">
              Last 7 Days
            </span>
          </div>
          <TrendChart readings={mockTrend} />
        </div>

        {/* Quick Actions */}
        <div className="mt-6 grid grid-cols-1 sm:grid-cols-3 gap-4 animate-fade-in" style={{ animationDelay: "300ms" }}>
          {[
            {
              to: "/calibrate",
              label: "Recalibrate",
              desc: "Update lighting reference",
              icon: "🔧",
              color: "from-neo-blue to-neo-blue/80",
            },
            {
              to: "/scan",
              label: "New Scan",
              desc: "Start a fresh analysis",
              icon: "📷",
              color: "from-neo-teal to-neo-teal/80",
            },
            {
              to: "/research",
              label: "View Research",
              desc: "Clinical validation data",
              icon: "📊",
              color: "from-purple-400 to-purple-400/80",
            },
          ].map(({ to, label, desc, icon, color }) => (
            <Link
              key={to}
              to={to}
              className="glass rounded-3xl p-5 shadow-card hover:shadow-glass hover:-translate-y-0.5 transition-all flex items-center gap-4"
            >
              <div className={`w-10 h-10 rounded-2xl bg-gradient-to-br ${color} flex items-center justify-center text-lg`}>
                {icon}
              </div>
              <div>
                <div className="font-display font-600 text-neo-dark text-sm">{label}</div>
                <div className="text-xs text-neo-muted font-body">{desc}</div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
};

export default DashboardPage;
