# Generated by Django 5.2.4 on 2026-05-09 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_interval_hours', models.IntegerField(default=4)),
                ('doctor_message', models.TextField(blank=True, null=True)),
                ('alert_level', models.CharField(default='info', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
